/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pack;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JLabel;

/**
 *
 * @author marma
 */
public class Panel extends javax.swing.JFrame {
 Snake Panel;
 public static int score = -1;
 
    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
        this.setLocationRelativeTo(null);
        Panel = new Snake(800,30);
        this.add(Panel);
        Panel.setBounds(10,10,800,800);
        Panel.setOpaque(false);
        Fondo fondo = new Fondo(800,30);
        this.add(fondo);
        fondo.setBounds(10,10,800,800);
        this.requestFocus(true);
       // public static int score;
       //this.jLabel1.setText(String.valueOf(score));
       this.jLabel1.setText(String.valueOf(score));
    }
public static void punto(int score){
    String puntuacion = String.valueOf(score);
    //puntoMostrar(puntuacion);
    new Panel().puntoMostrar(puntuacion);
    //this.jLabel1.setText(score);
}
public  void puntoMostrar(String score){
this.jLabel1.setText(score);
    //this.jLabel1.setText(score);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jButton2.setText("  ⇧ ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(" ⇦");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("⇩");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("⇨");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(883, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(623, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    private class TAdapter extends KeyAdapter {
//
//        @Override
//        public void keyPressed(KeyEvent e) {
//
//            int key = e.getKeyCode();
//
//            if ((key == KeyEvent.VK_LEFT)) {
//             Panel.cambiardireccion("iz");
//             System.out.println("iz");
//            }
//
//            if ((key == KeyEvent.VK_RIGHT)) {
//             System.out.println("de");
//             Panel.cambiardireccion("de");
//            }
//
//            if ((key == KeyEvent.VK_UP)) {
//             Panel.cambiardireccion("ar");
//             System.out.println("ar");
//            }
//
//            if ((key == KeyEvent.VK_DOWN)) {
//             Panel.cambiardireccion("ab");
//             System.out.println("ab");
//            }
//        }
//    }
//    class MyKeyAdapter extends KeyAdapter{
//        public void keyPressed(KeyEvent k){
//                switch(k.getKeyCode()){
//                case (KeyEvent.VK_S):
//                    Panel.cambiardireccion("ab");
//                    System.out.println("ab");
//                    
//                    break;
//                case (KeyEvent.VK_UP):
//                    if(direction != 'D' && !keyInput){
//                        direction = 'U';
//                        keyInput = true;
//                    }
//                    break;
//                case (KeyEvent.VK_LEFT):
//                    if(direction != 'R' && keyInput == false){
//                        direction = 'L';
//                        keyInput = true;
//                    }
//                    break;
//                case (KeyEvent.VK_RIGHT):
//                    if(direction != 'L' && keyInput == false){
//                        direction = 'R';
//                        keyInput = true;
//                    }
//                    break;
//                case (KeyEvent.VK_F2):
//                    if(!timer.isRunning()){
//                        startGame();
//                    }
//                    break;
//                case KeyEvent.VK_ESCAPE:
//					parentFrame.switchToLobbyPanel();
//					break;
//            }   
//        }
//        }
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
//     if(evt.getKeyCode()==KeyEvent.VK_D){
//         System.out.println("de");
//     }
        switch (evt.getKeyCode()) {
         case KeyEvent.VK_D:
             System.out.println("de");
             Panel.cambiardireccion("de");
             //System.out.println("de");
             break;
         case KeyEvent.VK_W:
             Panel.cambiardireccion("ar");
             System.out.println("ar");
             break;
         case KeyEvent.VK_S:
             Panel.cambiardireccion("ab");
             System.out.println("ab");
             break;
         case KeyEvent.VK_A:
             Panel.cambiardireccion("iz");
             System.out.println("iz");
             break;
         default:
             break;
     }
//          switch (evt.getKeyCode()) {
//         case KeyEvent.VK_LEFT:
//             Panel.cambiardireccion("de");
//             break;
//         case KeyEvent.VK_UP:
//             Panel.cambiardireccion("ar");
//             break;
//         case KeyEvent.VK_S:
//             Panel.cambiardireccion("ab");
//             break;
//         case KeyEvent.VK_A:
//             Panel.cambiardireccion("iz");
//             break;
//         default:
//             break;
//     }
    }//GEN-LAST:event_formKeyPressed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
//     if(evt.getKeyCode()==KeyEvent.VK_D){
//         System.out.println("de");
//     }
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Panel.cambiardireccion("ar");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    Panel.cambiardireccion("iz");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     Panel.cambiardireccion("ab");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 Panel.cambiardireccion("de");   
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
